version: 3.0.0
services:
    nginx:
        image: 'nginx:latest'
        volumes:
            - './:/var/www'
            - './_docker/nginx/conf.d:/etc/nginx/conf.d'
        ports:
            - '8876:80'
        depends_on:
            - app
        container_name: IDS_nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - './:/var/www'
        container_name: IDS
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
volumes:
    sail-mysql:
        driver: local
